num_1 = input ("Ingrese el primer numero:")
num_2 = input ("Ingrese el segundo numero:")
suma = float(num_1) + float(num_2)
resta = float(num_1) - float(num_2)
multiplicacion = float(num_1) * float(num_2)
division = float(num_1) / float(num_2)
potencia = float(num_1) ** float(num_2)
raiz_cuadrada = float(num_1) ** (1/2)
modulo = float(num_1) % float(num_2)
print(f"La suma es:{suma}, la resta es:{resta}, la multiplicacion es:{multiplicacion}, la division es:{division}, la potencia es:{potencia}, la raiz cuadrada es:{raiz_cuadrada}, el modulo es:{modulo}")